# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 542d7d3d5032069664762311d2bb82733b2571b243415a92882f6b9f0df0376878b353080676cc8ab8e0463cf13f3ff17c5caa1422eb382cdf5a71325892c93e

test:
  secret_key_base: 0e8e5ae6915affcd8d147984739978731410cd72eddd3785add65c94bc1be40b86c2d242aee1133ab7d09126eaffb1edcca5e2e3d86bac0190f7c13a699db504

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
